### PR TITLE
Homepage task

### PR DESCRIPTION
**Pull request by amar-waghmare**
Hi ,

I have completed homepage task please review it.

### CODE REVIEW

**Review by RajRatna77 — APPROVED** [review]
All is good. Code is approved.

**Review by Nilesh7174 — COMMENTED** [review]
all is good approved

**Review by SANDEPATIL — APPROVED** [review]
all is good

**Review by Swapnil7872 — APPROVED** [review]
Approved

**Review by Nilesh7174 — APPROVED** [review]

**Pull request merged**
